In [166]:
from aocd.models import Puzzle

puzzle = Puzzle(year=2022, day=20)

def parses(input):
    return [int(i) for i in input.strip().split('\n')]
data = parses(puzzle.input_data)

In [6]:
sample = parses('1\n2\n-3\n3\n-2\n0\n4')

In [379]:
from collections import deque


In [404]:
q = deque([1,2,3])

In [405]:
q.rotate(0)

In [406]:
q

deque([1, 2, 3])

In [384]:
q.rotate(-q.index(2))

In [385]:
q

deque([2, 3, 1])

In [386]:
1j.real

0.0

In [417]:
from collections import deque
def mix_queue(data, rounds):
    N = len(data)
    values = [(n,i) for i,n in enumerate(data)]
    queue = deque(values)
    for _ in range(rounds):
        for val in values:
            j = queue.index(val)
            queue.rotate(-j)
            n, i = queue.popleft()
            moves = n % (N-1)
            queue.rotate(-moves)
            queue.append((n,i))
    for i, (n,_) in enumerate(queue):
        if n == 0:
            break
    return sum(queue[(i+1000*j)%N][0] for j in range(1,4))
            

In [420]:
mix_queue(data,1)

9945

2

In [373]:
def mix_indices(data, rounds):
    N = len(data)
    indices = list(range(N))
    
    for _ in range(rounds):
        for i in range(N):
            current_pos = indices.index(i)
            indices.pop(current_pos)
            next_pos = ((current_pos+data[i]) % (N-1))
            indices.insert(next_pos, i)
    j = indices.index(data.index(0))
    return sum( data[indices[(j+1000*i)%N]] for i in range(1,4))

def solve_a(data):
    return mix_indices(data, 1)

def solve_b(data):
    data = [i*811589153 for i in data]
    return mix_indices(data, 10)

In [378]:
solve_b(data)

3338877775442

In [369]:
mix(data,1)

9945

In [367]:
mix(sample,1)

3

In [363]:
coordinates(mix(sample,1))

3

In [368]:
coordinates(mix(data,1))

AttributeError: 'int' object has no attribute 'index'

In [349]:
a = [10,20,30]

In [350]:
a.pop(0)

10

In [351]:
a

[20, 30]

In [352]:
a.insert(1,10)

In [353]:
a

[20, 10, 30]

In [311]:
class ListNode:    
    def __init__(self, val, next=None, prev=None):
        self.val = val
        self.next = next
        self.prev = prev
    def __repr__(self):
        return repr((self.prev.val, self.val, self.next.val))
    
    def __eq__(self, other):
        return repr(self) == repr(other)
    
    def print(node):
        l = [node.val]
        first = node
        while True:
            node = node.next
            if node == first:
                break
            l.append(node.val)
        print(l)

In [326]:
def mix(data, rounds):
    class ListNode:    
    def __init__(self, val, next=None, prev=None):
        self.val = val
        self.next = next
        self.prev = prev
        
    N = len(data)
    nodes = [ListNode(i) for i in data]
    for i, _ in enumerate(data):
        nodes[i].next = nodes[(i+1)%N]
        nodes[i].prev = nodes[i-1]
        
    for _ in range(rounds):
        for n in nodes:
            steps = (n.val % (N-1))
            if steps == 0: 
                continue
            dst = n
            for _ in range(steps):
                dst = dst.next
            # 8 pointers need to be changed
            # patch n out
            n.prev.next, n.next.prev = n.next, n.prev
            dst_next = dst.next 
            dst.next, dst_next.prev = n, n
            n.prev, n.next = dst, dst_next

    #compute coords
    for node in nodes:
        if node.val == 0:
            break
    total = 0
    for i in range(1,3001):
        node = node.next
        if i % 1000 == 0:
            total += node.val
    return total
    

In [328]:
def coordinates(nodes):
    for node in nodes:
        if node.val == 0:
            break
    total = 0
    for i in range(1,3001):
        node = node.next
        if i % 1000 == 0:
            total += node.val
    return total

In [329]:
def solve_a(data):
    return coordinates(mix(data,1))
        

In [330]:
solve_a(data)

9945

In [331]:
def solve_b(data):
    data = [i*811589153 for i in data]
    return coordinates(mix(data,10))

In [332]:
solve_b(sample)

1623178306

In [333]:
solve_b(data)

3338877775442

In [305]:
def mix(data, verbose=False):
    N = len(data)
    nodes = [ListNode(i) for i in data]
    for i, _ in enumerate(data):
        nodes[i].next = nodes[(i+1)%N]
        nodes[i].prev = nodes[i-1]
    for n in nodes:        
        for _ in range(abs(n.val)):
            if n.val > 0:
                dst = n.next
                n_prev, dst_next = n.prev, dst.next
                n.prev, n.next = dst, dst_next
                dst.prev, dst.next = n_prev, n
                n_prev.next, dst_next.prev = dst, n
            else:
                dst = n.prev
                n_next, dst_prev = n.next, dst.prev
                n.prev, n.next = dst_prev, dst
                dst.prev, dst.next = n, n_next
                n_next.prev, dst_prev.next = dst, n
    return nodes
    
        

In [306]:
mix(sample, True)

[1, 2, -3, 3, -2, 0, 4]
1
[(2, 1, -3), (4, 2, 1), (1, -3, 3), (-3, 3, -2), (3, -2, 0), (-2, 0, 4), (0, 4, 2)]
[1, -3, 3, -2, 0, 4, 2]
2
[(4, 1, -3), (-3, 2, 3), (1, -3, 2), (2, 3, -2), (3, -2, 0), (-2, 0, 4), (0, 4, 1)]
[1, -3, 2, 3, -2, 0, 4]
-3
[(4, 1, 2), (1, 2, 3), (-2, -3, 0), (2, 3, -2), (3, -2, -3), (-3, 0, 4), (0, 4, 1)]
[1, 2, 3, -2, -3, 0, 4]
3
[(4, 1, 2), (1, 2, -2), (-2, -3, 0), (0, 3, 4), (2, -2, -3), (-3, 0, 3), (3, 4, 1)]
[1, 2, -2, -3, 0, 3, 4]
-2
[(-2, 1, 2), (1, 2, -3), (2, -3, 0), (0, 3, 4), (4, -2, 1), (-3, 0, 3), (3, 4, -2)]
[1, 2, -3, 0, 3, 4, -2]
0
[(-2, 1, 2), (1, 2, -3), (2, -3, 0), (0, 3, 4), (4, -2, 1), (-3, 0, 3), (3, 4, -2)]
[1, 2, -3, 0, 3, 4, -2]
4
[(-2, 1, 2), (1, 2, -3), (2, -3, 4), (0, 3, -2), (3, -2, 1), (4, 0, 3), (-3, 4, 0)]
[1, 2, -3, 4, 0, 3, -2]


[(-2, 1, 2),
 (1, 2, -3),
 (2, -3, 4),
 (0, 3, -2),
 (3, -2, 1),
 (4, 0, 3),
 (-3, 4, 0)]

In [307]:
solve_a(sample)

3

In [309]:
solve_a(data)

9945

In [308]:
mix([1,2,3])

[(3, 1, 2), (1, 2, 3), (2, 3, 1)]

In [266]:
mix([1,2])

1
[1]
2
[1]


[(2, 1, 1), (2, 2, 2)]

In [262]:
s1 = np.arange(1,10).tolist()

In [263]:
s1

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [12]:
np.roll(sample, -1)

array([ 2, -3,  3, -2,  0,  4,  1])

In [17]:
np.iinfo(np.int16)

iinfo(min=-32768, max=32767, dtype=int16)

In [21]:
np.array(data)

array([ 9192,  9640, -1159, ...,  1182,  1707,  2813])

In [258]:
solve_a(sample)

3

In [259]:
solve_a(data)

-19628

In [94]:
solve_a(data)

3530

In [96]:
np.arange(12

AttributeError: 'numpy.ndarray' object has no attribute 'where'

In [136]:
np.roll(np.arange(12),-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  0])

In [177]:
def mix(data):
    N = len(data)
    values = np.array(data, dtype=np.int32)
    order = data.copy()
#     print(values)
    for v in order:
        if v == 0: continue
        print(v, np.where(values==v))
        i = np.where(values==v)[0].item()

        j = (i + v) % N if v > 0 else (i+v-1) % N
#         print(v,i,j)
        if j > i:
#             print(values[i:j+1])
            values[i:j+1] = np.roll(values[i:j+1], -1)
        if j < i:
#             print(values[j:i+1])
            values[j+1:i+1] = np.roll(values[j+1:i+1], 1)
        
#         k = np.where(values==1)[0].item()
#         print(np.roll(values, -k))
#         print(values)
    return values

In [178]:
def solve_a(data):
    N = len(data)
    values = mix(data)
    print(np.where(values==0))
    j = np.where(values==0)[0].item()
    return sum((values[(j+1000*i)%N] for i in range(1,4)))

In [179]:
mix(sample)

1 (array([0]),)
2 (array([0]),)
-3 (array([1]),)
3 (array([2]),)
-2 (array([2]),)
4 (array([5]),)


array([ 1,  2, -3,  4,  0,  3, -2], dtype=int32)

In [180]:
solve_a(sample)

1 (array([0]),)
2 (array([0]),)
-3 (array([1]),)
3 (array([2]),)
-2 (array([2]),)
4 (array([5]),)
(array([4]),)


3

In [181]:
solve_a(data)

9192 (array([ 0, 98]),)


ValueError: can only convert an array of size 1 to a Python scalar

In [182]:
sum(( i == 9192 for i in data))

2

In [22]:
# def solve_a(data):
#     data = np.array(data, dtype=np.int16)
#     order = data.copy()
#     for i in order:
#         j = np.where(data == i)
#         k = j + i
        