In [12]:
from aocd.models import Puzzle

puzzle = Puzzle(year=2021, day=5)

def parses(input):
    x = [parse.parse('{:d},{:d} -> {:d},{:d}', line).fixed for line in input.strip().split('\n')]
    return np.array(x)

data = parses(puzzle.input_data)

In [13]:
sample = parses("""0,9 -> 5,9
8,0 -> 0,8
9,4 -> 3,4
2,2 -> 2,1
7,0 -> 7,4
6,4 -> 2,0
0,9 -> 2,9
3,4 -> 1,4
0,0 -> 8,8
5,5 -> 8,2""")

In [14]:
def overlapHV(points):
    xmin, ymin = points.min(0).reshape(2,2).min(0)
    xmax, ymax = points.max(0).reshape(2,2).max(0)
    board = np.zeros(((xmax-xmin)+1,(ymax-ymin)+1))
    points -= np.array([[xmin, ymin, xmin, ymin]])
    for x1, y1, x2, y2 in points:
        if x1 == x2 or y1 == y2:
            if x1 > x2:
                x1, x2 = x2, x1
            if y1 > y2:
                y1, y2 = y2, y1
            board[x1:x2+1,y1:y2+1] += 1
    return (board > 1).sum()

In [4]:
overlapHV(data)

6005

In [5]:
overlapHV(sample)

5

In [6]:
def overlap(points, part='a'):
    xmin, ymin = points.min(0).reshape(2,2).min(0)
    xmax, ymax = points.max(0).reshape(2,2).max(0)
    board = np.zeros(((xmax-xmin)+1,(ymax-ymin)+1))
    points -= np.array([[xmin, ymin, xmin, ymin]])
    for x1, y1, x2, y2 in points:
        if (x1 == x2 or y1 == y2) or part == 'b':
            xs = np.arange(x1,x2+1) if x1 <= x2 else np.arange(x1,x2-1,-1)
            ys = np.arange(y1,y2+1) if y1 <= y2 else np.arange(y1,y2-1,-1)
            board[xs,ys] += 1
    return (board > 1).sum()

In [7]:

def overlap(points, part="a"):
    board = defaultdict(int)
    for x1, y1, x2, y2 in points:
        if (x1 == x2 or y1 == y2) or part == "b":
            if x1 < x2:
                xs = range(x1, x2 + 1)
            elif x1 > x2:
                xs = range(x1, x2 - 1, -1)
            else:
                xs = itertools.repeat(x1)
            if y1 < y2:
                ys = range(y1, y2 + 1)
            elif y1 > y2:
                ys = range(y1, y2 - 1, -1)
            else:
                ys = itertools.repeat(y1)
            for x, y in zip(xs, ys):
                board[x, y] += 1
    print(sum(board.values()))
    return sum(1 for v in board.values() if v > 1)

In [8]:
def overlap_npc(points, part='a'):
    points = np.array(points).reshape((len(points), 2, 2))
    allpoints = np.vstack([
        p[0] + np.outer(np.arange(1+p.ptp(0).max()), np.sign(p[1]-p[0]))
        for p in points if p.ptp(0).min() == 0 or part == 'b'
    ])
    _, counts = np.unique(allpoints, axis=0, return_counts=True)
    return (counts > 1).sum()

In [17]:
x1, x2, y = 11, 566, 981
a = np.linspace(x1, x2, x2-x1+1, dtype=np.int32)
b = np.linspace([x1,y], [x2,y], x2-x1+1, dtype=np.int32)[:,0]
b2 = np.linspace([x1,y], [x2,y], x2-x1+1, dtype=np.float32)[:,0].astype(np.int32)
c = np.arange(x1, x2+1)

print(a.shape, b.shape, c.shape)
print((a == c).all())
print((b == c).all())
print((b2 == c).all())

print()

for i in np.where(b != c)[0]:
    print(a[i-2:i+3])
    print(b[i-2:i+3])
    print()

(556,) (556,) (556,)
True
False
True

[380 381 382 383 384]
[380 381 381 383 384]

[386 387 388 389 390]
[386 387 387 389 390]

[392 393 394 395 396]
[392 393 393 395 396]

[398 399 400 401 402]
[398 399 399 401 402]

[404 405 406 407 408]
[404 405 405 407 408]

[410 411 412 413 414]
[410 411 411 413 414]

[416 417 418 419 420]
[416 417 417 419 420]



In [11]:
x1, x2, y = 11, 566, 981
a = np.linspace(x1, x2, x2-x1+1, dtype=np.int64)
b = np.linspace([x1,y], [x2,y], x2-x1+1, dtype=np.int64)[:,0]
b2 = np.linspace([x1,y], [x2,y], x2-x1+1, dtype=np.float64)[:,0].astype(np.int64)
c = np.arange(x1, x2+1)

print(a.shape, b.shape, c.shape)
print((a == c).all())
print((b == c).all())
print((b2 == c).all())

print()

for i in np.where(b != c)[0]:
    print(a[i-2:i+3])
    print(b[i-2:i+3])
    print()

(556,) (556,) (556,)
True
False
False

[380 381 382 383 384]
[380 381 381 383 384]

[386 387 388 389 390]
[386 387 387 389 390]

[392 393 394 395 396]
[392 393 393 395 396]

[398 399 400 401 402]
[398 399 399 401 402]

[404 405 406 407 408]
[404 405 405 407 408]

[410 411 412 413 414]
[410 411 411 413 414]

[416 417 418 419 420]
[416 417 417 419 420]



In [8]:
b = np.linspace([x1,y], [x2,y], x2-x1+1, dtype=np.int32)[:,0]
b2 = np.linspace([x1,y], [x2,y], x2-x1+1, dtype=np.float32)[:,0].astype(np.int32)

print((b == b2).all())

for i in np.where(b != b2)[0]:
    print(b[i-2:i+3])
    print(b2[i-2:i+3])
    print()

True


In [9]:
b = np.linspace([x1,y], [x2,y], x2-x1+1, dtype=np.int64)[:,0]
b2 = np.linspace([x1,y], [x2,y], x2-x1+1, dtype=np.float64)[:,0].astype(np.int64)

print((b == b2).all())
print((c == b2).all())


for i in np.where(c != b2)[0]:
    print(c[i-2:i+3])
    print(b2[i-2:i+3])
    print()

True
True


In [5]:
x1, x2, y = 11, 566, 981
a = np.linspace(x1, x2, x2-x1+1, dtype=np.float32).astype(np.int32)
b = np.linspace([x1,y], [x2,y], x2-x1+1, dtype=np.float32)[:,0].astype(np.int32)
c = np.arange(x1, x2+1)
print(a.shape, b.shape, c.shape)
print((a == c).all())
print((b == c).all())

for i in np.where(b != c)[0]:
    print(a[i-2:i+3])
    print(b[i-2:i+3])
    print()

(556,) (556,) (556,)
True
True


In [6]:
x1, x2, y = 40, 100, 200
a = np.linspace(x1, x2, x2-x1+1, dtype=np.int32)
b = np.linspace([x1,y], [x2,y], x2-x1+1, dtype=np.int32)[:,0]
c = np.arange(x1, x2+1)
print(a.shape, b.shape, c.shape)
print((a == c).all())
print((b == c).all())

for i in np.where(b != c)[0]:
    print(a[i-2:i+3])
    print(b[i-2:i+3])
    print()



(61,) (61,) (61,)
True
True


In [425]:
( == ).all()

<ipython-input-425-6db3832f1084>:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  (np.linspace(np.array([981,566]),np.array([981,11]),567, dtype=np.int32)[:,1] == np.arange(566,10,-1)).all()


AttributeError: 'bool' object has no attribute 'all'

In [423]:
data

array([[  0, 404, 404,   0],
       [735,  73, 316,  73],
       [981, 566, 981,  11],
       ...,
       [672, 152, 672, 842],
       [468, 825, 468, 911],
       [673, 731, 267, 325]])

In [3]:
np.arange(1+p.ptp(0).max())

NameError: name 'p' is not defined

In [402]:
np.sign(p[1]-p[0])

array([ 0, -1])

In [418]:
overlap(data)

114149


6005

In [365]:
overlap(data, 'b')

206226


23848

In [393]:
data[:3]

array([[  0, 404, 404,   0],
       [735,  73, 316,  73],
       [981, 566, 981,  11]])

In [399]:
p = np.array([981, 566, 981,  11]).reshape(2,2)

In [376]:
p

array([[981, 566],
       [981,  11]])

In [390]:
_, c = np.unique(np.linspace(p[0], p[1], p.ptp(0).max(), dtype=np.int32), axis=0, return_counts=True)

In [391]:
c

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [387]:
p[0], p[1]

(array([981, 566]), array([981,  11]))

In [388]:
556

556

In [389]:
np.linspace(p[0])

556

In [374]:
data[:3]

array([[  0, 404, 404,   0],
       [735,  73, 316,  73],
       [981, 566, 981,  11]])

In [396]:
overlap_npc(sample)

20
[[0 9]
 [2 9]
 [3 4]
 [7 4]]
Counter({1: 12, 2: 4})


4

In [419]:
overlap_npc(data)

114149
[[ 21 765]
 [ 26 334]
 [ 26 417]
 ...
 [977 677]
 [981 407]
 [981 472]]
Counter({1: 101966, 2: 5832, 3: 173})


6005

In [369]:
overlap(data[:3])

976


0